package GuiAndControllers;
/**
 * modify habit frame, add and update
 * @author luod1
 */
import Model.Habit;
import Model.ModeTranslators;
import Model.UserInfo;
import Translators.HabitsApapter;
import Translators.HabitsInterface;
import javax.swing.JOptionPane;


public class ModifyHabitFrame extends javax.swing.JFrame {

    private final int defaultZero = 0;
    public static int rowId;
    HabitsInterface habits;

    /**
     * Creates new form gui_AddHabit
     */
    public ModifyHabitFrame() {
        this.habits = new HabitsApapter();
        initComponents();
        //if is update, set the habit information to text
        if (MainHabitFrame.habit != null) {
            this.jtx_Title.setText(MainHabitFrame.habit.getTitle());
            this.jtxa_description.setText(MainHabitFrame.habit.getDescription());
            this.jlb_isActive.setText(MainHabitFrame.habit.getIsActive());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtx_Title = new javax.swing.JTextField();
        jbt_AddHabit = new javax.swing.JButton();
        jbt_CancelAddH = new javax.swing.JButton();
        jbt_UpdateHabit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxa_description = new javax.swing.JTextArea();
        jlb_isActive = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(134, 226, 213));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Habits");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Habit Title:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Description: ");

        jtx_Title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_TitleActionPerformed(evt);
            }
        });

        jbt_AddHabit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt_AddHabit.setText("ADD");
        jbt_AddHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_AddHabitActionPerformed(evt);
            }
        });

        jbt_CancelAddH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt_CancelAddH.setText("Back");
        jbt_CancelAddH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_CancelAddHActionPerformed(evt);
            }
        });

        jbt_UpdateHabit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbt_UpdateHabit.setText("Update");
        jbt_UpdateHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_UpdateHabitActionPerformed(evt);
            }
        });

        jtxa_description.setColumns(20);
        jtxa_description.setRows(5);
        jScrollPane1.setViewportView(jtxa_description);

        jlb_isActive.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlb_isActive.setText("status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbt_CancelAddH)
                                .addComponent(jtx_Title, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jbt_AddHabit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbt_UpdateHabit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jlb_isActive, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_CancelAddH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtx_Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addComponent(jlb_isActive)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_AddHabit)
                    .addComponent(jbt_UpdateHabit))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * back to the main habit frame
     * @param evt 
     */
    private void jbt_CancelAddHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_CancelAddHActionPerformed
        // TODO add your handling code here:
        new MainHabitFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_CancelAddHActionPerformed

    private void jtx_TitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_TitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_TitleActionPerformed

    /**
     * add new habit, and open the main frame
     * @param evt 
     */
    private void jbt_AddHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_AddHabitActionPerformed
        // TODO add your handling code here:
        addNewHabit();
        new MainHabitFrame().setVisible(true);
        dispose();

    }//GEN-LAST:event_jbt_AddHabitActionPerformed

    /**
     * update the habit, and open the main frame
     * @param evt 
     */
    private void jbt_UpdateHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_UpdateHabitActionPerformed
        // TODO add your handling code here:
        if (MainHabitFrame.habit != null) {
            update();
            new MainHabitFrame().setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_jbt_UpdateHabitActionPerformed

    /**
     * insert new habit to database
     * @return 
     */
    private boolean addNewHabit() {
        //take the habits information
        UserInfo user = ModeTranslators.user;
        String title = this.jtx_Title.getText();
        String description = this.jtxa_description.getText();
        int streakDays = defaultZero;
        String isActive = "disable";
        String name = user.getUsername();
        Habit habit = new Habit(title, description, streakDays, isActive, name);
        // insert the habit 
        boolean insert = habits.insertHabit(habit);
        if (insert) {
            JOptionPane.showMessageDialog(null, "insert success!");
            new MainHabitFrame().quaryAll();
            this.jtx_Title.setText("");
            this.jtxa_description.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "fail to save habit!");
        }
        return insert;
    }

    /**
     * update the habits which is modified
     */
    private void update() {
        int id = ModifyHabitFrame.rowId;
        String title = this.jtx_Title.getText();
        String description = this.jtxa_description.getText();
        int streakDays = defaultZero;
        String isActive = this.jlb_isActive.getText();
        Habit habit = new Habit(id, title, description, streakDays, isActive);
        //update the habits information at database
        boolean update = habits.updateHabit(habit);
        if (update) {
            JOptionPane.showMessageDialog(null, "modify success!");
            MainHabitFrame.habit = null;
            this.jtx_Title.setText("");
            this.jtxa_description.setText("");
            this.rowId = this.defaultZero;
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "modify fail!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyHabitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyHabitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyHabitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyHabitFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyHabitFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_AddHabit;
    private javax.swing.JButton jbt_CancelAddH;
    private javax.swing.JButton jbt_UpdateHabit;
    private javax.swing.JLabel jlb_isActive;
    private javax.swing.JTextField jtx_Title;
    private javax.swing.JTextArea jtxa_description;
    // End of variables declaration//GEN-END:variables
}
