package GuiAndControllers;

/**
 * GUI and controller for user register
 *
 * @author dan
 */
import Translators.UserApapter;
import Model.UserInfo;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import Translators.UserInterface;
import java.util.UUID;

public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form gui_register
     */
    public RegisterFrame() {
        initComponents();
    }
    
    UserInterface tms = new UserApapter();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtx_RegUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtx_RegEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtx_RegPassword = new javax.swing.JTextField();
        jbt_RegBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jbt_RegOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(134, 226, 213));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Register");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Login Name         ");

        jtx_RegUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_RegUserNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("E-mail                ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password  ");

        jbt_RegBack.setBackground(new java.awt.Color(255, 255, 255));
        jbt_RegBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_RegBack.setText("BACK");
        jbt_RegBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_RegBackActionPerformed(evt);
            }
        });

        jLabel5.setText("*(length 6-10, low charcter )");

        jbt_RegOk.setBackground(new java.awt.Color(255, 255, 255));
        jbt_RegOk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_RegOk.setText("OK");
        jbt_RegOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_RegOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbt_RegBack))
                            .addComponent(jtx_RegUserName)
                            .addComponent(jtx_RegEmail)
                            .addComponent(jtx_RegPassword)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jbt_RegOk, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jbt_RegBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtx_RegUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtx_RegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtx_RegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbt_RegOk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtx_RegUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_RegUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_RegUserNameActionPerformed

    /**
     * validate Email and password, call AddNewUser register user and close this
     * frame
     *
     * @param evt
     */
    private void jbt_RegOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_RegOkActionPerformed
        // TODO add your handling code here:
        if (validateUsername(this.jtx_RegUserName.getText()) && validateEmail(this.jtx_RegEmail.getText())
                && validatePassword(this.jtx_RegPassword.getText())) {
            addNewUser();
            new LoginFrame().setVisible(true);
            dispose();//close this frame
        } 


    }//GEN-LAST:event_jbt_RegOkActionPerformed

    /**
     * open login frame and close this frame
     *
     * @param evt
     */
    private void jbt_RegBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_RegBackActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        dispose();
    }//GEN-LAST:event_jbt_RegBackActionPerformed

    /**
     * *
     * Validate email in current format
     *
     * @param _email
     * @return
     */
    public boolean validateEmail(String _email) {
        Pattern p = Pattern.compile("[\\w!#$%&'*+/=?^_`{|}~-]+(?:\\.[\\w!#$%&'*+/=?^_`{|}~-]+)*@(?:[\\w](?:[\\w-]*[\\w])?\\.)+[\\w](?:[\\w-]*[\\w])?");
        Matcher m = p.matcher(_email);
        if (m.find() && m.group().equals(_email) && emailIsTaken(_email)) {
            return true;
        } else {
            this.jtx_RegEmail.setText("");
            JOptionPane.showMessageDialog(null, "Invalid email", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }

    /**
     * *
     * Validate password in current format
     *
     * @param _password
     * @return
     */
    public boolean validatePassword(String _password) {
        Pattern lowerCase = Pattern.compile("(?=.*[a-z]).{6,10}");
        Matcher m = lowerCase.matcher(_password);
        if (m.find() && m.group().equals(_password)) {
            return true;
        } else {
            this.jtx_RegPassword.setText("");
            JOptionPane.showMessageDialog(null, "Password need in lowercase and 6 to 10 longer", "Error", JOptionPane.WARNING_MESSAGE);
            return false;

        }

    }

    /**
     * find username is ready taken or not
     *
     * @param _username
     * @return
     */
    public boolean validateUsername(String _username) {
        //UserInterface tms = new UserApapter();
        String UserName = this.jtx_RegUserName.getText();
        boolean isExistName = tms.findUserName(UserName);
        if (isExistName == true) {
            JOptionPane.showMessageDialog(null, "This username is ready taken ");
            
            return false;
        }
        return true;
    }
    
    /**
     * find username is ready taken or not
     *
     * @param _username
     * @return
     */
    public boolean emailIsTaken(String _email) {
        //UserInterface tms = new UserApapter();
        String email = this.jtx_RegEmail.getText();
        boolean isExistEmail = tms.isExistEmail(email);
        if (isExistEmail == true) {
            JOptionPane.showMessageDialog(null, "This email is ready taken ");
            
            return false;
        }
        return true;
    }
    
    /**
     * insert new user to database
     */
    private void addNewUser() {
        //UserInterface tms = new UserApapter();
        String UserName = this.jtx_RegUserName.getText();
        String Password = this.jtx_RegPassword.getText();
        String Email = this.jtx_RegEmail.getText();
        String id = UUID.randomUUID().toString();
        UserInfo u = new UserInfo(id, UserName, Password, Email);
        boolean insert = tms.insertUser(u);
        if (insert == true) {
            JOptionPane.showMessageDialog(null, "register success!");
            this.jtx_RegUserName.setText("");
            this.jtx_RegPassword.setText("");
            this.jtx_RegEmail.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "fail to register!");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbt_RegBack;
    private javax.swing.JButton jbt_RegOk;
    private javax.swing.JTextField jtx_RegEmail;
    private javax.swing.JTextField jtx_RegPassword;
    private javax.swing.JTextField jtx_RegUserName;
    // End of variables declaration//GEN-END:variables
}
